const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Plugins.Tilemap,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Anchor,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{BgSopa: 0},
	{apellOriSopa: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{tupaiOriSopa: 0},
	{Touch: 0},
	{TiledBackground: 0},
	{Pin: 0},
	{tanah: 0},
	{Tilemap: 0},
	{Tilemap2: 0},
	{Sprite: 0},
	{Text: 0},
	{Sprite2: 0},
	{SpriteFont: 0},
	{SKOR: 0},
	{SpriteFont2: 0},
	{Sprite3: 0},
	{Anchor: 0},
	{TeksNyawa: 0},
	{perangkappOriSopa: 0},
	{perangkap: 0},
	{awalan: 0},
	{title: 0},
	{awalan2: 0},
	{OlehSopa: 0},
	{skor: 0},
	{jumlahApel: 0},
	{nyawa: 0}
];

self.InstanceType = {
	BgSopa: class extends self.ISpriteInstance {},
	apellOriSopa: class extends self.ISpriteInstance {},
	tupaiOriSopa: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	tanah: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	SKOR: class extends self.ISpriteFontInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TeksNyawa: class extends self.ISpriteFontInstance {},
	perangkappOriSopa: class extends self.ISpriteInstance {},
	perangkap: class extends self.ISpriteInstance {},
	awalan: class extends self.ISpriteInstance {},
	title: class extends self.ISpriteInstance {},
	awalan2: class extends self.ISpriteInstance {},
	OlehSopa: class extends self.ITextInstance {}
}